OmbelievableYoga/config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'faq/index'
  get 'welcome/index'
  get 'donations/index'
  get 'workouts/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :poses, :only => [:index, :show]
  root 'welcome#index'
end

OmbelievableYoga/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

OmbelievableYoga/app/models/pose.rb
class Pose < ApplicationRecord
end

OmbelievableYoga/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

OmbelievableYoga/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

OmbelievableYoga/app/controllers/donations_controller.rb
class DonationsController < ApplicationController
end

OmbelievableYoga/app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

OmbelievableYoga/app/controllers/poses_controller.rb
class PosesController < ApplicationController
  def index
    @poses = Pose.all
  end
  def show
    @pose = Pose.find(params[:id])
  end
end

OmbelievableYoga/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

OmbelievableYoga/app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
end

OmbelievableYoga/app/helpers/about_helper.rb
module AboutHelper
end

OmbelievableYoga/app/helpers/application_helper.rb
module ApplicationHelper
end

OmbelievableYoga/app/helpers/donations_helper.rb
module DonationsHelper
end

OmbelievableYoga/app/helpers/faq_helper.rb
module FaqHelper
end

OmbelievableYoga/app/helpers/poses_helper.rb
module PosesHelper
end

OmbelievableYoga/app/helpers/welcome_helper.rb
module WelcomeHelper
end

OmbelievableYoga/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

OmbelievableYoga/app/views/about/index.html.erb
<div id="about" class="container-fluid text-center">
  <div class="row">
    <div class="col-sm-12">
      <br>
      <h2>About</h2><br>
      <h4>Ombelievable Yoga can help you destress and ecnourage gentle exercise and stretching as part of a healthy lifestyle.</h4><br>
      <p>Our mandate is to help you find your inner peace even (especially) when school can be stressing you out. We strive to maintain our web-site and bring you yoga workouts that are masterfully curated by our outstanding yogi instructors. To do this we need your help!</p>
    </div>
  </div>
</div>
<div id="contact" class="container-fluid text-center" style="background-color: #eee;">
  <h2 class="text-center">Creators</h2>
  <div class="row">
    <div class="col-sm-4">
      <p class="text-center"><strong>Sherry Wang</strong></p><br>
      <a href="#demo" data-toggle="collapse">
        <img src="<%=asset_path('Sherry.jpg')%>" style="width: 160px; height: 200px; border-radius: 100%;">
      </a>
      <div id="demo" class="collapse">
        <p>Group and Task Manager</p>
        <p>swang261@uottawa.ca</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Meina Oria</strong></p><br>
      <a href="#demo2" data-toggle="collapse">
        <img src="<%=asset_path('Meina.jpg')%>" style="width: 160px; height: 200px; border-radius: 100%;">
      </a>
      <div id="demo2" class="collapse">
        <p>Evaluation and Implementation Manager</p>
        <p>moria097@uottawa.ca</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Ashley Labelle</strong></p><br>
      <a href="#demo3" data-toggle="collapse">
        <img src="<%=asset_path('Ash.jpg')%>" style="width: 160px; height: 200px; border-radius: 100%;">
      </a>
      <div id="demo3" class="collapse">
        <p>Documentation and Design Manager</p>
        <p>alabe101@uottawa.ca</p>
      </div>
    </div>
  </div>
</div>

OmbelievableYoga/app/views/donations/index.html.erb
<div class="container-fluid text-center">
  <br>
  <div class="row content">
    <h2>Donate</h2>
    <div>
      <p>Our mandate is to help you find your inner peace even (especially) when school can be stressing you out. We strive to maintain our web-site and bring you yoga workouts
      that are masterfully curated by our outstanding yogi instructors. To do this we need your help! Please support us if you love Ombelievable Yoga and you can't wait to see us flourish
      and bring you the latest in your Ombelievable journey! </p>
    </div>
    <hr>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="2X6NBA3AFU9FN">
    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
    <div>
    <br>
    <p>We appreciate your support!</p>
    <hr>
    </div>
  </div>
</div>

OmbelievableYoga/app/views/faq/index.html.erb
<div id="portfolio" class="container-fluid text-center bg-grey">
  <br>
  <h2>Frequently Asked Questions</h2><br>

    <div style="margin-left: 32px;margin-right: 32px;">
    <button class="accordion">What is Yoga?</button>
    <div class="panel">
        <p>The word yoga, from the Sanskrit word yuj, means to yoke or bind, and is often interpreted as "union" or a method of discipline. A male who practices yoga is called a yogi, a female practitioner, a yogini.</p>

        <p>The Indian sage Patanjali is believed to have collated the practice of yoga into the Yoga Sutra an estimated 2,000 years ago. The Sutra is a collection of 195 statements that serves as a philosophical guidebook for most of the yoga that is practiced today. It also outlines eight limbs of yoga: the yamas (restraints), niyamas (observances), asana (postures), pranayama (breathing), pratyahara (withdrawal of senses), dharana (concentration), dhyani (meditation), and samadhi (absorption). As we explore these eight limbs, we begin by refining our behavior in the outer world, and then we focus inwardly until we reach samadhi (liberation, enlightenment).</p>

        <p>Today, most people practicing yoga are engaged in the third limb, asana, which is a program of physical postures designed to purify the body and provide the physical strength and stamina required for long periods of meditation.</p>
    </div>

    <button class="accordion">What does Om mean?</button>
    <div class="panel">
        <p>Om is a mantra, or vibration, that is traditionally chanted at the beginning and end of yoga sessions. It is said to be the sound of the universe. What does that mean?</p>

        <p>Somehow the ancient yogis knew what scientists today are telling us—that the entire universe is moving. Nothing is ever solid or still. Everything that exists pulsates, creating a rhythmic vibration that the ancient yogis acknowledged with the sound of Om. We may not always be aware of this sound in our daily lives, but we can hear it in the rustling of the autumn leaves, the waves on the shore, the inside of a seashell.</p>

        <p>Chanting Om allows us to recognize our experience as a reflection of how the whole universe moves—the setting sun, the rising moon, the ebb and flow of the tides, the beating of our hearts. As we chant Om, it takes us for a ride on this universal movement, through our breath, our awareness, and our physical energy, and we begin to sense a bigger connection that is both uplifting and soothing.</p>
    </div>

    <button class="accordion">How many times per week should I practice?</button>
    <div class="panel">
        <p>Yoga is amazing—even if you only practice for one hour a week, you will experience the benefits of the practice. If you can do more than that, you will certainly experience more benefits. I suggest starting with two or three times a week, for an hour or an hour and a half each time. If you can only do 20 minutes per session, that's fine too. Don't let time constraints or unrealistic goals be an obstacle—do what you can and don't worry about it. You will likely find that after a while your desire to practice expands naturally and you will find yourself doing more and more.</p>
    </div>

    <button class="accordion">How is Yoga different drom stretching or other kinds of fitness?</button>
    <div class="panel">
        <p>Unlike stretching or fitness, yoga is more than just physical postures. Patanjali's eight-fold path illustrates how the physical practice is just one aspect of yoga. Even within the physical practice, yoga is unique because we connect the movement of the body and the fluctuations of the mind to the rhythm of our breath. Connecting the mind, body, and breath helps us to direct our attention inward. Through this process of inward attention, we learn to recognize our habitual thought patterns without labeling them, judging them, or trying to change them. We become more aware of our experiences from moment to moment. The awareness that we cultivate is what makes yoga a practice, rather than a task or a goal to be completed. Your body will most likely become much more flexible by doing yoga, and so will your mind.</p>
    </div>

    <button class="accordion">I'm not flexible — can I do Yoga?</button>
    <div class="panel">
        <p>Yes! You are a perfect candidate for yoga. Many people think that they need to be flexible to begin yoga, but that's a little bit like thinking that you need to be able to play tennis in order to take tennis lessons. Come as you are and you will find that yoga practice will help you become more flexible.</p>

        <p>This newfound agility will be balanced by strength, coordination, and enhanced cardiovascular health, as well as a sense of physical confidence and overall well-being.</p>
    </div>

    <button class="accordion">What do I need to begin?</button>
    <div class="panel">
        <p>All you really need to begin practicing yoga is your body, your mind, and a bit of curiosity. But it is also helpful to have a pair of yoga leggings, or shorts, and a t-shirt that's not too baggy. No special footgear is required because you will be barefoot. It's nice to bring a towel to class with you. As your practice develops you might want to buy your own yoga mat, but most studios will have mats and other props available for you.</p>
    </div>

        <button class="accordion">Why Are You Supposed to Refrain From Eating 2–3 Hours Before Class?</button>
    <div class="panel">
        <p>In yoga practice we twist from side to side, turn upside down, and bend forward and backward. If you have not fully digested your last meal, it will make itself known to you in ways that are not comfortable. If you are a person with a fast-acting digestive system and are afraid you might get hungry or feel weak during yoga class, experiment with a light snack such as yogurt, a few nuts, or juice about 30 minutes to an hour before class.</p>
    </div>

    <script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight){
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        }
      });
    }
    </script>
    </div>

</div>

OmbelievableYoga/app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">
  <p style="font-size: 10px;">Ombelievable Yoga 2018, SEG3125 Project, University of Ottawa | This non-profit website is for educational purposes. Users are responsible for their own risk and injuries</p>
</footer>

OmbelievableYoga/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img src="<%= asset_path('logo-white.png') %>" style="width: 50px; height: 50px; float: left;">
      <a><%= link_to "mbelievableYoga", welcome_index_path, {:class =>"navbar-brand"}%></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ABOUT", about_index_path%></li>
        <li><%= link_to "POSES", poses_path%></li>
        <li><%= link_to "FAQ", faq_index_path%></li>
        <li><%= link_to "DONATION", donations_index_path%></li>
        <li><%= link_to workouts_index_path, class:"btn btn-workout btn-sm" do%><i class="glyphicon glyphicon-play"></i><% end %></a></li>

      </ul>
    </div>
  </div>
</nav>

OmbelievableYoga/app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
 <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render :partial => "layouts/navbar" %>
  </head>
  <body data-spy="scroll" data-target=".navbar" data-offset="60">
    <%= yield %>
  </body>
  <footer>
    <%= render :partial => "layouts/footer" %>
  </footer>
</html>

OmbelievableYoga/app/views/poses/index.html.erb
<div >
  <div class="row">
    <div class="col-sm-12 text-center">
      <br>
      <br>
      <br>
      <h2>Yoga Poses</h2>
      <p>Learn about the individual poses.</p>
    </div>
  </div>
<!--
  <div class="input-group">
    <input type="text" class="form-control" placeholder="Search for...">
    <span class="input-group-btn">
      <button id="searchByText" type="button" class="btn btn-default dropdown-toggle" style="border-radius: 0;" data-toggle="dropdown" aria-expanded="false">Search By <b>Title</b> <span class="caret"></span></button>
      <ul class="dropdown-menu" id="searchBy" role="menu">
        <li><a href="#Title">Title</a></li>
        <li><a href="#Keyword">Keyword</a></li>
        <li><a href="#Author">Author</a></li>
      </ul>
      <button class="btn btn-default" type="button" onclick="window.location.href='search.html';">Search</button>
    </span>
  </div>
-->


  <div id="Beginner" class="container-fluid bg-3 text-center" style="padding-top:50px; padding-bottom: 50px;">

    <% @poses.each do |pose| %>
       <div class="col-sm-6 col-md-4 center">
         <div class="thumbnail">
           <img src="<%=pose.imageSrc%>" class="img-responsive" style="width:480px; height:480px;" alt="Image">
           <div class="caption">
             <h3><%= pose.title%> </h3>
             <a href="#<%= pose.videoId%>" data-toggle="collapse" class="btn btn-default">
               <div>
                 <h5>Pose Details</h5>
               </div>
             </a>
             <div id="<%= pose.videoId%>" class="collapse">
               <p><%= pose.description%></p>
             </div>
           </div>
         </div>
       </div>
       <% end %>
    <br>

    <!-- <div class="row">
      <div class="col-sm-6 col-md-4">

          <div class="thumbnail">
              <img src="<%= asset_path('Poses/1.jpg')%>" class="img-responsive" style="width:100%" alt="Image">
                <div class="caption">
                  <h3>Seated Forward Bend</h3>
                </div>
                <a href="#seatedForwardBend" data-toggle="collapse" class="btn btn-default">
                  <div>
                    <h5>Pose Details</h5>
                  </div>
                </a>
                <div id="seatedForwardBend" class="collapse">
                  <p></p>
                </div>
              </div>
            </div>




              </div> -->

              <br>
            </div>
          </div>

OmbelievableYoga/app/views/poses/show.html.erb
<div class="container-fluid text-center">
<h2> <%= @pose.title %></h2>
<div class="row">
  <div class="col-sm-8">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="@pose.imageSrc" alt="Image">
        </div>
      </div>

    </div>
  </div>

  <div class="col-sm-4">
    <br>
    <center>
    <button class="btn btn-default" type="button" onclick="window.location.href='#Description';" style="height: 60px; width: 320px; font-size: 20px;">Description</button>
    <button class="btn btn-default" type="button" onclick="window.location.href='#Steps';" style="height: 60px; width: 320px; font-size: 20px;">Steps</button>
    </center>
  </div>

</div>
<hr>
</div>

<div id="Description" class="container text-center" style="padding-top:50px; padding-bottom: 50px;">
  <h3>Description</h3>
  <p><%= @pose.title %></p>
</div>

<div id="Steps" class="container text-center" style="padding-top:50px; padding-bottom: 50px;">
  <h3>Steps</h3>
  <h5>Step 1:</h5>
  <p>Lorem ipsum...</p>
  <h5>Step 2:</h5>
  <p>Lorem ipsum...</p>
  <h5>Step 3:</h5>
  <p>Lorem ipsum...</p>
  <h5>Step 4:</h5>
  <p>Lorem ipsum...</p>
  <h5>Step 5:</h5>
  <p>Lorem ipsum...</p>
</div>

<div class="container text-center">
  <hr>
  <br>
  <div class="row">
    <div class="col-sm-3">

    </div>
    <div class="col-sm-3">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Pose name</p>
    </div>
    <div class="col-sm-3">
      <button class="btn btn-default" type="button" onclick="window.location.href='tutorial.html';" style="height: 60px; width: 250px; font-size: 16px;">See video tutorial</button>
    </div>
  </div>
  <hr>
</div>

<div class="container text-center">
  <h3>Suggestions</h3>
  <br>
  <div class="row">
    <div class="col-sm-2">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Partner 1</p>
    </div>
    <div class="col-sm-2">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Partner 2</p>
    </div>
    <div class="col-sm-2">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Partner 3</p>
    </div>
    <div class="col-sm-2">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Partner 4</p>
    </div>
    <div class="col-sm-2">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Partner 5</p>
    </div>
    <div class="col-sm-2">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Partner 6</p>
    </div>
  </div>
</div><br>

OmbelievableYoga/app/views/welcome/_rating.html.erb
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<div class="container-fluid text-center">
<div class="stars">
  <form action="">
    <input class="star star-5" id="star-5" type="radio" name="star"/>
    <label class="star star-5" for="star-5"></label>
    <input class="star star-4" id="star-4" type="radio" name="star"/>
    <label class="star star-4" for="star-4"></label>
    <input class="star star-3" id="star-3" type="radio" name="star"/>
    <label class="star star-3" for="star-3"></label>
    <input class="star star-2" id="star-2" type="radio" name="star"/>
    <label class="star star-2" for="star-2"></label>
    <input class="star star-1" id="star-1" type="radio" name="star"/>
    <label class="star star-1" for="star-1"></label>
  </form>
</div>
</div>

OmbelievableYoga/app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Hey there, Yogi.</h1>
  <img src="<%= asset_path('peas.png') %>" style="width: 90px; height: 62px;">
  <p>We hope you find your inner <span style="color: #ddff8e;">peas!</span></p>
  <a><%= link_to "Start Workout", workouts_index_path, {:class =>"btn btn-default btn-lg"}%></a>
</div>

OmbelievableYoga/app/views/workouts/index.html.erb
<div class="container-fluid text-center">
  <h2>Workout Session</h2>
  <div class="row content">
      <!-- from: https://developers.google.com/youtube/iframe_api_reference -->

      <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
      <center><div id="player"></div></center>

      <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');
      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '390',
          width: '640',
          playerVars:{
            listType: 'playlist',
            list: 'PLdg7F0XYN8z15IWGNU0YBJy5HQpfmPV2H',
            autoplay: 1
          },
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange,
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.setShuffle(true);
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }


      </script>
      <div>
      <br>
      <h3>Repeat 10 times on each side.</h3>
    </div>
    </div>
  </div>